import { Avatar, Card, CardHeader, Container, Divider, Grid, IconButton, SvgIcon, Typography } from '@mui/material'
import Head from 'next/head'
import MuiLink from '@mui/material/Link'
import styles from '../styles/Home.module.css'
import IconPack from 'simple-icons'
import { useState } from 'react'
import SettingsIcon from '@mui/icons-material/Settings';
import { useRouter } from 'next/router'
import Search from '../components/Search'
import Link from 'next/link'
import { WeatherIcon } from '../icons/WeatherIcon'

export default function Home() {
  const [bookmarks, setBookmarks] = useState(new Array(8).fill(null).map((_, index) => ({
    id: index + 1,
    name: 'Portainer',
    url: 'https://portainer.navneetlal.in',
    icon: 'portainer'
  })))
  const router = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth='md' sx={{ my: 5 }}>
        <Search />
      </Container>

      <Container maxWidth="lg" sx={{ my: 5 }}>
        <Grid container justifyContent={"space-between"}>
          <Grid item sm={8}>
            <Typography variant="h3">
              Good Morning!
            </Typography>
          </Grid>
          <Grid container item sm={4} justifyContent={'flex-end'}>
            <Grid item sx={{ mx: 1 }}>
              <WeatherIcon isDay={1} weatherStatusCode={1063} />
            </Grid>
            <Grid item>
              <Typography>24.4&deg;C</Typography>
              <Divider />
              <Typography>44%</Typography>
            </Grid>
          </Grid>
        </Grid>
      </Container>

      <Container maxWidth="lg">
        <Link href="/applications"><Typography variant='h6'>APPLICATIONS</Typography></Link>
        <Grid container justifyContent={"normal"}>
          {
            bookmarks.map(bookmark => {
              return (
                <Card elevation={0} key={bookmark.id} sx={{ my: 1, mr: 1 }}>
                  <MuiLink underline='none' color="MenuText" target="_blank" rel="noreferrer" href={bookmark.url}>
                    <CardHeader
                      avatar={
                        <Avatar aria-label="icon" variant="square" sx={{ backgroundColor: 'unset' }}>
                          <SvgIcon inheritViewBox sx={{ color: `#${IconPack.Get(bookmark.icon).hex}` }}>
                            <path d={IconPack.Get(bookmark.icon).path} />
                          </SvgIcon>
                        </Avatar>
                      }
                      title={bookmark.name}
                      subheader={bookmark.url}
                    />
                  </MuiLink>
                </Card>
              )
            })
          }
        </Grid>
      </Container>

      <Container maxWidth="lg">
        <Link href="/bookmarks"><Typography variant='h6'>BOOKMARKS</Typography></Link>
        <Grid container justifyContent={"normal"}>
          {
            bookmarks.map(bookmark => {
              return (
                <Card elevation={0} key={bookmark.id} sx={{ my: 1, mr: 1 }}>
                  <MuiLink underline='none' color="MenuText" target="_blank" rel="noreferrer" href={bookmark.url}>
                    <CardHeader
                      avatar={
                        <Avatar aria-label="icon" variant="square" sx={{ backgroundColor: 'unset' }}>
                          <SvgIcon inheritViewBox sx={{ color: `#${IconPack.Get(bookmark.icon).hex}` }}>
                            <path d={IconPack.Get(bookmark.icon).path} />
                          </SvgIcon>
                        </Avatar>
                      }
                      title={bookmark.name}
                      subheader={bookmark.url}
                    />
                  </MuiLink>
                </Card>
              )
            })
          }
        </Grid>
      </Container>
      <IconButton size='large' sx={{ position: 'fixed', bottom: '10px', left: '10px' }} onClick={() => router.push('/settings')}>
        <SettingsIcon fontSize='large' />
      </IconButton>
    </div>
  )
}
